const minecraftIdeas = [
  "Castle", "Farmhouse", "Treehouse", "Rollercoaster", "Skybase", "Statue", "Underground Bunker", "Waterfall", 
  "Library", "Dungeon", "Space Station", "Windmill", "Aquarium", "Lighthouse", "Tower", "Ship", "Maze", 
  "Theme Park", "Race Track", "Temple", "Floating Island", "Village", "Colosseum", "Bridge", "Zoo", "Bank", 
  "Clock Tower", "Hidden Base", "Battle Arena", "Observatory", "Fort", "Hot Air Balloon", "Underwater Base", 
  "Sculpture", "Monastery", "Secret Passage", "Water Park", "Giant Tree", "Museum", "Fountain", "Prison", "Stadium",
  "Campsite", "Library", "Train Station", "Dungeon", "Airport", "Clock Tower", "Factory", "Mansion", "Pixel Art",
  "Farm", "Mine Shaft", "Marketplace", "Water Tower", "Greenhouse", "Fairy Tale House", "Windmill", "Rollercoaster",
  "Cyberpunk City", "Medieval Town", "Futuristic Base", "Survival Shelter", "Solar Farm", "Barn", "Highway", 
  "Dragon Lair", "Alchemist Lab", "Ice Castle", "Hobbit Hole", "Cathedral", "Sewer System", "Minecart System",
  "Volcano", "Rainbow Bridge", "Ice Cream Shop", "Secret Hideout", "Moon Base", "Tavern", "Clockwork Tower",
  "Pirate Ship", "Helicopter Pad", "Skyscraper", "Cavern City", "Archery Range", "Infinity Pool", "Dinosaur Park",
  "Castle Gate", "Water Slide", "Giant Pyramid", "Hidden Library", "Adventure Hub", "Alien Spaceship", "Fishing Dock",
  "Floating Garden", "Rainbow Road", "Supermarket", "Cargo Ship", "Underground Railroad", "Gas Station", "Metro Station",
  "Haunted Mansion", "Royal Palace", "Hanging Gardens", "Jungle Temple", "Dojo", "Sky Sanctuary", "Carnival", "Statue Garden",
  "Train Tracks", "Watch Tower", "Beach Resort", "Artificial Island", "Dungeon Entrance", "Wishing Well", "Marketplace", 
  "Bazaar", "Amusement Park", "Moon Colony", "Dragon Statue", "Giant Clock", "River Dock", "Ocean Base", "Underworld City",
  "Shrine", "Mystic Cavern", "Woodland Hideout", "Research Facility", "Pixel Art Display", "Space Elevator", "UFO Landing Pad",
  "Steampunk Factory", "Deep Sea Lab", "Enchanted Forest", "Meteor Crater", "Underground Kingdom", "Temple Ruins", 
  "Water Town", "Space Outpost", "Nordic Village", "Sunken Ship", "Circus", "Minecart Track", "Grand Hotel", "Lava Fortress",
  "Farming Complex", "Cave Town", "Treetop Village", "Abandoned Mine", "Giant Chessboard", "Clock Tower Ruins", 
  "Opera House", "Trading Post", "Theater", "High-Tech Base", "Grand Staircase", "Archipelago", "Sky Kingdom",
  "Giant Piano", "Mecha Hangar", "Mountain Retreat", "Jungle City", "River Village", "Underground Library", "Artificial Waterfall",
  "Safari Park", "Petting Zoo", "Parkour Course", "Giant Rock Formation", "Arena", "Space Dock", "Ancient Ruins",
  "Luxury Mansion", "Submarine Base", "Fire Station", "Garden Maze", "Observatory Dome", "Crystal Cave", "Hot Springs", 
  "Steamworks", "Zen Garden", "Lost City", "Floating Fortress", "Neon City", "Labyrinth", "Royal Chambers",
  "Pirate Cove", "Gothic Tower", "Futuristic Train", "Research Laboratory", "Colossal Statues", "Rainforest Habitat",
  "Candy Land", "Massive Treehouse", "Giant Aquarium", "Fantasy Island", "Sky Train", "Industrial Complex", 
  "Mountain Tunnel", "Secret Laboratory", "Train Depot", "Luxury Resort", "Bank Vault", "Rocket Launch Pad", "Artificial Beach",
  "Car Factory", "Warehouse District", "Magic School", "Mystic Tower", "Racing Circuit", "Dark Dungeon", "Gas Giant Base",
  "Chess Arena", "Holographic Stadium", "Oceanic Platform", "Sky Harbor", "Jungle Observatory", "Asteroid Mine",
  "Sci-Fi City", "Space Dome", "Terraforming Base", "Underwater Cave", "Ruined Temple", "Floating Ruins", "Hidden Oasis",
  "Giant Wind Turbine", "Ancient Crypt", "Treasure Vault", "Desert Palace", "Oasis Village", "War Fortress",
  "Giant Tree Sculpture", "Magnet Tower", "Tropical Resort", "Deep Sea Castle", "Railway System", "Snow Fortress",
  "Futuristic Prison", "Dark Mage Tower", "Abandoned Factory", "Royal Guard Barracks", "Dragon Coliseum", "Secret Vault",
  "Medieval Marketplace", "Gothic Cathedral", "Science Lab", "Portal Gate", "Ender City", "Nether Fortress", 
  "Crystal Tower", "Coral Reef Sanctuary", "Cavern City", "Lost Temple", "Castle Dungeon", "Floating Library",
  "Garden Palace", "Rainbow Tower", "Bio Dome", "Cyber Arena", "Magical Island", "Orbital Station", "Neon Tower",
  "Sky Temple", "Alien Habitat", "Moon Research Center", "Tropical Island Base", "Clockwork City", "Deep Sea Observatory",
  "Titanic Replica", "Anime Village", "Film Studio", "Wild West Town", "Hologram Park", "Artificial Reef",
  "Island Fortress", "Sandcastle", "Gravity Chamber", "Endless Stairs", "Mystic Lake", "Ancient Grotto", "Solar Observatory"
];
// ideas were generated by microsoft copilot

function roll(){
    let roll = Math.floor(Math.random() * minecraftIdeas.length)
    document.getElementById('skibidi').innerHTML=minecraftIdeas[roll]
}